// packages/ui/src/svelte/ExportMenu.svelte
<script lang="ts">
  import { Download, FileText, FileCode, FileType } from 'lucide'
  import type { IconNode } from 'lucide'
  import { ExportEvents, type ExportFormat } from 'sagak-core'
  import type { EditorContext } from 'sagak-core'
  import { icon } from '../elements/icon'

  /**
   * 내보내기 메뉴 — 목록 버튼에서 만든 드롭다운 얼개를 **그대로** 씁니다.
   *
   * `[k=dropdown]` 안에 `[commandfor]` 달린 트리거와 `<dialog
   * k="dropdown-content">`. 위치는 CSS 앵커가 잡고, 항목을 눌러도 메뉴는
   * 스스로 닫히지 않으니 직접 닫습니다. 두 번째로 옮기면서 확인한 것은
   * **얼개가 반복된다는 것**이지 새로운 문제가 아닙니다.
   *
   * 다른 점은 항목 안쪽이 두 줄(이름 + 설명)이라는 것뿐입니다.
   *
   * ## `filename` 은 아무도 안 넘깁니다
   *
   * Preact 판에도 있던 prop 인데 툴바가 `<ExportMenu />` 로만 씁니다. 기본값
   * `'document'` 가 그대로 나가고 있었습니다. **고치지 않고 그대로 둡니다** —
   * 파일 이름을 어디서 받아 올지는 문서 줄(`document-bar`)까지 옮긴 뒤에
   * 봐야 할 이야기입니다.
   */

  interface Props {
    editor: EditorContext | null
    filename?: string
  }

  const { editor, filename = 'document' }: Props = $props()

  const menuId = $props.id()

  let menuEl: HTMLDialogElement

  interface Option {
    format: ExportFormat
    label: string
    node: IconNode
    description: string
  }

  const OPTIONS: Option[] = [
    {
      format: 'html',
      label: 'HTML',
      node: FileCode,
      description: 'Web page format',
    },
    {
      format: 'markdown',
      label: 'Markdown',
      node: FileType,
      description: 'Plain text with formatting',
    },
    {
      format: 'text',
      label: 'Plain Text',
      node: FileText,
      description: 'No formatting',
    },
  ]

  function exportAs(format: ExportFormat): void {
    menuEl.close()
    editor?.eventBus.emit(ExportEvents.EXPORT_DOWNLOAD, { format, filename })
  }
</script>

<div k="dropdown">
  <button
    type="button"
    commandfor={menuId}
    data-part="icon-button"
    title="Export"
    aria-label="Export"
    onclick={() => menuEl.show()}
  >
    {@html icon(Download, 18).outerHTML}
  </button>

  <dialog bind:this={menuEl} id={menuId} k="dropdown-content" aria-label="Export as">
    {#each OPTIONS as option (option.format)}
      <button
        type="button"
        k="dropdown-menu-item"
        onclick={() => exportAs(option.format)}
      >
        <span style="display: flex; align-items: center; gap: 10px">
          {@html icon(option.node, 16).outerHTML}
          <span>
            <span style="display: block">{option.label}</span>
            <span style="display: block; font-size: 11px; opacity: 0.6">
              {option.description}
            </span>
          </span>
        </span>
      </button>
    {/each}
  </dialog>
</div>

// packages/ui/src/components/export-menu/export-menu.tsx
import type { ComponentChildren } from 'preact'
import { useId } from 'preact/hooks'
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
} from 'kinu'
import { Download, FileText, FileCode, FileType } from 'lucide-preact'
import { ExportEvents, type ExportFormat } from 'sagak-core'
import { useEditorContext } from '../../context/editor-context'
import { ToolbarButton } from '../toolbar-button/toolbar-button'

const ICON_SIZE = 18

interface ExportOption {
  format: ExportFormat
  label: string
  icon: ComponentChildren
  description: string
}

const exportOptions: ExportOption[] = [
  {
    format: 'html',
    label: 'HTML',
    icon: <FileCode size={16} />,
    description: 'Web page format',
  },
  {
    format: 'markdown',
    label: 'Markdown',
    icon: <FileType size={16} />,
    description: 'Plain text with formatting',
  },
  {
    format: 'text',
    label: 'Plain Text',
    icon: <FileText size={16} />,
    description: 'No formatting',
  },
]

export interface ExportMenuProps {
  filename?: string
}

export function ExportMenu({
  filename = 'document',
}: ExportMenuProps): ComponentChildren {
  const { eventBus } = useEditorContext()
  // `DropdownMenuItem` 은 항목을 눌러도 메뉴를 닫지 않습니다.
  // `link-dialog` 와 같은 이유로 id 를 직접 잡아 `<dialog>` 를 닫습니다.
  const menuId = useId()

  const handleExport = (format: ExportFormat): void => {
    const menu = document.getElementById(menuId)
    if (menu instanceof HTMLDialogElement) {
      menu.close()
    }
    eventBus.emit(ExportEvents.EXPORT_DOWNLOAD, { format, filename })
  }

  return (
    <DropdownMenu id={menuId}>
      {/* Trigger 는 자체 요소를 만들지 않고 자식에 commandfor/command 를 얹습니다 */}
      <DropdownMenuTrigger>
        <ToolbarButton title="Export">
          <Download size={ICON_SIZE} aria-hidden="true" />
        </ToolbarButton>
      </DropdownMenuTrigger>

      <DropdownMenuContent id={menuId} aria-label="Export as">
        {exportOptions.map((option) => (
          <DropdownMenuItem
            key={option.format}
            onClick={() => handleExport(option.format)}
          >
            <span style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              {option.icon}
              <span>
                <span style={{ display: 'block' }}>{option.label}</span>
                <span style={{ display: 'block', fontSize: 11, opacity: 0.6 }}>
                  {option.description}
                </span>
              </span>
            </span>
          </DropdownMenuItem>
        ))}
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
