// packages/ui/src/svelte/ImageDialog.svelte
<script lang="ts">
  import { Image as ImageIcon, Link as LinkIcon, Upload } from 'lucide'
  import { ContentEvents } from 'sagak-core'
  import type { EditorContext } from 'sagak-core'
  import { icon } from '../elements/icon'
  import {
    ALLOWED_TYPES,
    MAX_FILE_SIZE,
    getSelectedImage,
  } from '../components/image-dialog/image-dialog.shared'

  /**
   * 이미지 다이얼로그 — **Svelte 로 방향을 바꾼 이유를 확인하는 자리**입니다.
   *
   * 지금까지 옮긴 것들은 상태가 한둘이라 어느 렌더러든 비슷했습니다. 여기는
   * 상태가 **아홉 개**고 서로 물려 있습니다(모드·URL·대체문구·크기 둘·편집
   * 여부·업로드 오류·미리보기·고른 파일). nanotags 로 했다면 이 아홉을
   * `paint()` 하나에 손으로 엮어야 했습니다.
   *
   * Svelte 에서는 `$state` 로 두고 마크업이 알아서 따라옵니다. **이 차이가
   * 방향 전환의 값입니다** — 툴바 버튼에서는 안 보이던 것이 여기서 보입니다.
   *
   * ## 다이얼로그는 여전히 네이티브입니다
   *
   * kinu 를 걷어내면서 확인한 대로 `<dialog>` + `showModal()` 을 그대로 씁니다.
   * 포커스 트랩·Esc·백드롭은 브라우저가 합니다. 렌더러를 바꿔도 이 부분은
   * 안 바뀝니다.
   *
   * ## 열 때의 순서가 중요합니다
   *
   * 1. 여는 클릭에서 **선택 영역을 저장**하고 기존 값을 미리 채웁니다
   * 2. 적용은 **닫은 다음 프레임**에 합니다 — 닫히기 전에 되돌리면 다이얼로그가
   *    아직 포커스를 쥐고 있어 선택이 다시 풀립니다
   */

  interface Props {
    editor: EditorContext | null
  }

  const { editor }: Props = $props()

  type UploadMode = 'url' | 'file'

  let dialogEl: HTMLDialogElement
  let fileInput: HTMLInputElement | undefined = $state()

  let mode = $state<UploadMode>('url')
  let src = $state('')
  let alt = $state('')
  let width = $state('')
  let height = $state('')
  let isEditing = $state(false)
  let uploadError = $state<string | null>(null)
  let previewUrl = $state<string | null>(null)
  let selectedFile = $state<File | null>(null)

  const canSubmit = $derived(
    mode === 'url' ? src.trim().length > 0 : previewUrl !== null
  )

  const event = $derived(
    mode === 'file' || !isEditing
      ? ContentEvents.IMAGE_INSERT
      : ContentEvents.IMAGE_UPDATE
  )

  function resetUpload(): void {
    selectedFile = null
    previewUrl = null
    uploadError = null
  }

  function open(): void {
    editor?.selectionManager?.saveSelection()

    const img = getSelectedImage()
    src = img?.src ?? ''
    alt = img?.alt ?? ''
    width = img?.style.width ?? ''
    height = img?.style.height ?? ''
    isEditing = !!img
    mode = 'url'
    resetUpload()

    dialogEl.showModal()
  }

  /** 닫은 다음 프레임에 선택을 되돌리고 적용합니다 */
  function restoreThen(action: () => void): void {
    dialogEl.close()
    requestAnimationFrame(() => {
      editor?.selectionManager?.restoreSelection()
      action()
    })
  }

  function submit(): void {
    if (mode === 'file' && previewUrl) {
      const preview = previewUrl
      const name = selectedFile?.name
      restoreThen(() => {
        editor?.eventBus.emit(ContentEvents.IMAGE_INSERT, {
          src: preview,
          alt: alt.trim() || name,
          width: width.trim() || undefined,
          height: height.trim() || undefined,
        })
      })
      return
    }

    if (mode !== 'url') return

    const trimmed = src.trim()
    /* src 가 비어 있어도 닫기는 합니다 */
    if (!trimmed) {
      dialogEl.close()
      return
    }

    const payload = {
      src: trimmed,
      alt: alt.trim(),
      width: width.trim() || undefined,
      height: height.trim() || undefined,
    }
    const target = event
    restoreThen(() => editor?.eventBus.emit(target, payload))
  }

  function remove(): void {
    restoreThen(() => editor?.eventBus.emit(ContentEvents.IMAGE_DELETE))
  }

  /**
   * 파일 갈래는 **Preact 판의 로직을 그대로** 옮겼습니다.
   *
   * 이 갈래에는 검사가 없습니다 — `FileReader` 와 `DataTransfer` 를 흉내 내야
   * 하는데, 그렇게 만든 검사는 브라우저가 아니라 흉내를 검사하게 됩니다
   * (`test/image-dialog.browser.test.tsx` 에 적어 뒀습니다). 검사가 없는 만큼
   * **고치지 않고 옮기는 것**이 유일한 안전장치입니다.
   */
  function acceptFile(file: File): void {
    uploadError = null

    if (!ALLOWED_TYPES.includes(file.type)) {
      uploadError =
        'Invalid file type. Please select a JPEG, PNG, GIF, or WebP image.'
      return
    }
    if (file.size > MAX_FILE_SIZE) {
      uploadError = `File size exceeds ${MAX_FILE_SIZE / 1024 / 1024}MB limit.`
      return
    }

    selectedFile = file
    alt = file.name.replace(/\.[^/.]+$/, '')

    const reader = new FileReader()
    reader.onload = () => {
      previewUrl = reader.result as string
    }
    reader.readAsDataURL(file)
  }

  function onFileInput(e: Event): void {
    const file = (e.currentTarget as HTMLInputElement).files?.[0]
    if (file) acceptFile(file)
  }

  function onDrop(e: DragEvent): void {
    e.preventDefault()
    e.stopPropagation()
    const file = e.dataTransfer?.files?.[0]
    if (file && file.type.startsWith('image/')) acceptFile(file)
  }
</script>

<button
  type="button"
  data-part="icon-button"
  title="Insert Image"
  aria-label="Insert Image"
  onclick={open}
>
  {@html icon(ImageIcon, 18).outerHTML}
</button>

<dialog bind:this={dialogEl} k="dialog-content" aria-label={isEditing ? 'Edit Image' : 'Insert Image'}>
  <h2>{isEditing ? 'Edit Image' : 'Insert Image'}</h2>

  {#if !isEditing}
    <div role="group" aria-label="Image source">
      <button type="button" k="toggle" aria-pressed={mode === 'url'} onclick={() => (mode = 'url')}>
        {@html icon(LinkIcon, 16).outerHTML}
        URL
      </button>
      <button type="button" k="toggle" aria-pressed={mode === 'file'} onclick={() => (mode = 'file')}>
        {@html icon(Upload, 16).outerHTML}
        Upload
      </button>
    </div>
  {/if}

  {#if mode === 'url'}
    <div>
      <label k="label" for="image-url">Image URL *</label>
      <input
        id="image-url"
        k="input"
        type="text"
        bind:value={src}
        placeholder="https://example.com/image.jpg"
      />
    </div>
  {/if}

  {#if mode === 'file' && !isEditing}
    <div>
      <input
        bind:this={fileInput}
        type="file"
        accept={ALLOWED_TYPES.join(',')}
        onchange={onFileInput}
        style="display: none"
      />
      <!-- svelte-ignore a11y_click_events_have_key_events -->
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <div
        onclick={() => fileInput?.click()}
        ondrop={onDrop}
        ondragover={(e) => {
          e.preventDefault()
          e.stopPropagation()
        }}
      >
        {#if previewUrl}
          <img src={previewUrl} alt="Preview" style="max-width: 100%; max-height: 150px" />
          <p>{selectedFile?.name}</p>
          <button
            type="button"
            k="button"
            variant="outline"
            onclick={(e) => {
              e.stopPropagation()
              resetUpload()
              if (fileInput) fileInput.value = ''
            }}
          >
            Remove
          </button>
        {:else}
          {@html icon(Upload, 32).outerHTML}
          <p>Click to select or drag and drop</p>
          <p>JPEG, PNG, GIF, WebP (max 5MB)</p>
        {/if}
      </div>
      {#if uploadError}
        <p role="alert">{uploadError}</p>
      {/if}
    </div>
  {/if}

  <div>
    <label k="label" for="image-alt">Alt Text</label>
    <input id="image-alt" k="input" type="text" bind:value={alt} placeholder="Image description" />
  </div>

  <div style="display: flex; gap: 12px">
    <div style="flex: 1">
      <label k="label" for="image-width">Width</label>
      <input id="image-width" k="input" type="text" bind:value={width} placeholder="300px or 50%" />
    </div>
    <div style="flex: 1">
      <label k="label" for="image-height">Height</label>
      <input id="image-height" k="input" type="text" bind:value={height} placeholder="auto" />
    </div>
  </div>

  <div style="display: flex; gap: 8px; justify-content: flex-end">
    {#if isEditing}
      <button type="button" k="button" variant="destructive" onclick={remove}>Delete</button>
    {/if}
    <button type="button" k="button" variant="outline" onclick={() => dialogEl.close()}>
      Cancel
    </button>
    <button type="button" k="button" onclick={submit} disabled={!canSubmit}>
      {isEditing ? 'Update' : 'Insert'}
    </button>
  </div>
</dialog>

// packages/ui/src/components/image-dialog/image-dialog.tsx
import type { ComponentChildren, JSX } from 'preact'
import { useRef, useState } from 'preact/hooks'
import { Dialog, Button, Input, Label, ToggleGroup, Toggle } from 'kinu'
import { Image, Upload, Link } from 'lucide-preact'
import { ContentEvents } from 'sagak-core'
import { useEditorContext } from '../../context/editor-context'
import { useDialogHandle } from '../../hooks/use-dialog-handle'
import {
  ALLOWED_TYPES,
  MAX_FILE_SIZE,
  getSelectedImage,
} from './image-dialog.shared'
import { useSelectionDerived } from '../../hooks/use-selection-derived'
import { ToolbarButton } from '../toolbar-button/toolbar-button'

const ICON_SIZE = 18

type UploadMode = 'url' | 'file'


const dropZoneStyle: JSX.CSSProperties = {
  border: '2px dashed var(--sagak-chrome-border)',
  borderRadius: 8,
  padding: 24,
  textAlign: 'center',
  cursor: 'pointer',
}

export function ImageDialog(): ComponentChildren {
  const { eventBus } = useEditorContext()
  const [mode, setMode] = useState<UploadMode>('url')
  const [src, setSrc] = useState('')
  const [alt, setAlt] = useState('')
  const [width, setWidth] = useState('')
  const [height, setHeight] = useState('')
  const hasImage = useSelectionDerived(() => !!getSelectedImage(), false)
  const [isEditing, setIsEditing] = useState(false)
  const [uploadError, setUploadError] = useState<string | null>(null)
  const [previewUrl, setPreviewUrl] = useState<string | null>(null)
  const [selectedFile, setSelectedFile] = useState<File | null>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)
  const { id: dialogId, save, close, restoreThen } = useDialogHandle()

  const resetUploadState = (): void => {
    setSelectedFile(null)
    setPreviewUrl(null)
    setUploadError(null)
  }

  /** `commandfor` 가 다이얼로그를 여는 것과 같은 클릭에서 먼저 실행됩니다 */
  const handleOpen = (): void => {
    save()
    const img = getSelectedImage()
    if (img) {
      setSrc(img.src)
      setAlt(img.alt || '')
      setWidth(img.style.width || '')
      setHeight(img.style.height || '')
      setIsEditing(true)
      setMode('url')
    } else {
      setSrc('')
      setAlt('')
      setWidth('')
      setHeight('')
      setIsEditing(false)
      setMode('url')
    }
    resetUploadState()
  }

  const handleFileSelect = (file: File): void => {
    setUploadError(null)

    if (!ALLOWED_TYPES.includes(file.type)) {
      setUploadError(
        'Invalid file type. Please select a JPEG, PNG, GIF, or WebP image.'
      )
      return
    }

    if (file.size > MAX_FILE_SIZE) {
      setUploadError(
        `File size exceeds ${MAX_FILE_SIZE / 1024 / 1024}MB limit.`
      )
      return
    }

    setSelectedFile(file)
    setAlt(file.name.replace(/\.[^/.]+$/, ''))

    const reader = new FileReader()
    reader.onload = () => {
      setPreviewUrl(reader.result as string)
    }
    reader.readAsDataURL(file)
  }

  const handleFileInputChange = (
    e: JSX.TargetedEvent<HTMLInputElement, Event>
  ): void => {
    const file = e.currentTarget.files?.[0]
    if (file) {
      handleFileSelect(file)
    }
  }

  const handleDrop = (e: JSX.TargetedDragEvent<HTMLDivElement>): void => {
    e.preventDefault()
    e.stopPropagation()
    const file = e.dataTransfer?.files?.[0]
    if (file && file.type.startsWith('image/')) {
      handleFileSelect(file)
    }
  }

  const handleDragOver = (e: JSX.TargetedDragEvent<HTMLDivElement>): void => {
    e.preventDefault()
    e.stopPropagation()
  }

  const handleSubmit = (): void => {
    if (mode === 'file' && previewUrl) {
      restoreThen(() =>
        eventBus.emit(ContentEvents.IMAGE_INSERT, {
          src: previewUrl,
          alt: alt.trim() || selectedFile?.name,
          width: width.trim() || undefined,
          height: height.trim() || undefined,
        })
      )
      return
    }

    if (mode !== 'url') return

    const trimmedSrc = src.trim()
    // src 가 비어 있어도 닫기는 합니다
    if (!trimmedSrc) {
      close()
      return
    }

    const payload = {
      src: trimmedSrc,
      alt: alt.trim(),
      width: width.trim() || undefined,
      height: height.trim() || undefined,
    }

    restoreThen(() =>
      isEditing
        ? eventBus.emit(ContentEvents.IMAGE_UPDATE, payload)
        : eventBus.emit(ContentEvents.IMAGE_INSERT, payload)
    )
  }

  const canSubmit = (): boolean => {
    if (mode === 'url') {
      return src.trim().length > 0
    }
    return previewUrl !== null
  }

  const handleDelete = (): void => {
    restoreThen(() => eventBus.emit(ContentEvents.IMAGE_DELETE))
  }

  return (
    <Dialog id={dialogId}>
      <Dialog.Trigger>
        <ToolbarButton
          title="Insert Image"
          onClick={handleOpen}
          state={hasImage ? 'on' : undefined}
        >
          <Image size={ICON_SIZE} aria-hidden="true" />
        </ToolbarButton>
      </Dialog.Trigger>

      <Dialog.Content
        id={dialogId}
        aria-label={isEditing ? 'Edit Image' : 'Insert Image'}
      >
        <h2>{isEditing ? 'Edit Image' : 'Insert Image'}</h2>

        {!isEditing && (
          <ToggleGroup role="group" aria-label="Image source">
            <Toggle
              pressed={mode === 'url'}
              onClick={() => setMode('url')}
              type="button"
            >
              <Link size={16} />
              URL
            </Toggle>
            <Toggle
              pressed={mode === 'file'}
              onClick={() => setMode('file')}
              type="button"
            >
              <Upload size={16} />
              Upload
            </Toggle>
          </ToggleGroup>
        )}

        {mode === 'url' && (
          <div>
            <Label>Image URL *</Label>
            <Input
              type="text"
              value={src}
              onInput={(event) =>
                setSrc((event.currentTarget as HTMLInputElement).value)
              }
              placeholder="https://example.com/image.jpg"
            />
          </div>
        )}

        {mode === 'file' && !isEditing && (
          <div>
            <input
              ref={fileInputRef}
              type="file"
              accept={ALLOWED_TYPES.join(',')}
              onChange={handleFileInputChange}
              style={{ display: 'none' }}
            />
            <div
              onClick={() => fileInputRef.current?.click()}
              onDrop={handleDrop}
              onDragOver={handleDragOver}
              style={dropZoneStyle}
            >
              {previewUrl ? (
                <div>
                  <img
                    src={previewUrl}
                    alt="Preview"
                    style={{ maxWidth: '100%', maxHeight: 150 }}
                  />
                  <p>{selectedFile?.name}</p>
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={(event) => {
                      event.stopPropagation()
                      resetUploadState()
                      if (fileInputRef.current) {
                        fileInputRef.current.value = ''
                      }
                    }}
                  >
                    Remove
                  </Button>
                </div>
              ) : (
                <div>
                  <Upload size={32} aria-hidden="true" />
                  <p>Click to select or drag and drop</p>
                  <p>JPEG, PNG, GIF, WebP (max 5MB)</p>
                </div>
              )}
            </div>
            {uploadError && <p role="alert">{uploadError}</p>}
          </div>
        )}

        <div>
          <Label>Alt Text</Label>
          <Input
            type="text"
            value={alt}
            onInput={(event) =>
              setAlt((event.currentTarget as HTMLInputElement).value)
            }
            placeholder="Image description"
          />
        </div>

        <div style={{ display: 'flex', gap: 12 }}>
          <div style={{ flex: 1 }}>
            <Label>Width</Label>
            <Input
              type="text"
              value={width}
              onInput={(event) =>
                setWidth((event.currentTarget as HTMLInputElement).value)
              }
              placeholder="300px or 50%"
            />
          </div>
          <div style={{ flex: 1 }}>
            <Label>Height</Label>
            <Input
              type="text"
              value={height}
              onInput={(event) =>
                setHeight((event.currentTarget as HTMLInputElement).value)
              }
              placeholder="auto"
            />
          </div>
        </div>

        <div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end' }}>
          {isEditing && (
            <Button type="button" variant="destructive" onClick={handleDelete}>
              Delete
            </Button>
          )}
          <Dialog.Close>
            <Button type="button" variant="outline">
              Cancel
            </Button>
          </Dialog.Close>
          <Button type="button" onClick={handleSubmit} disabled={!canSubmit()}>
            {isEditing ? 'Update' : 'Insert'}
          </Button>
        </div>
      </Dialog.Content>
    </Dialog>
  )
}
