// packages/ui/src/svelte/AutocompletePopover.svelte
<script lang="ts">
  import { AutocompleteEvents } from 'sagak-core'
  import type { EditorContext } from 'sagak-core'

  /**
   * 자동 완성 팝오버 — **마지막으로 남은 Preact 컴포넌트**였습니다.
   *
   * 툴바 안이 아니라 편집 영역 위에 떠야 해서 앱이 직접 붙입니다. 그래서
   * 툴바를 다 옮기고도 혼자 남아 있었습니다.
   *
   * ## 네 이벤트를 듣습니다
   *
   * 보이기 · 숨기기 · 위아래 이동 · 확정. 상태는 코어가 정하고 여기는
   * 그리기만 합니다 — 어떤 단어를 제안할지, 어디에 띄울지는 플러그인이
   * 페이로드에 실어 보냅니다.
   *
   * ## 확정에는 갈래가 둘입니다
   *
   * 마우스로 고르면 그 단어를 실어 발행합니다. 키보드로 확정하면 페이로드가
   * 비어 오는데, 그때는 **지금 고른 것**을 실어 다시 발행합니다. 페이로드가
   * 이미 있으면 그건 우리가 보낸 것이므로 흘려보냅니다 — 안 그러면 무한히
   * 되돌아옵니다.
   */

  interface Props {
    editor: EditorContext
  }

  const { editor }: Props = $props()

  let visible = $state(false)
  let suggestions = $state<string[]>([])
  let prefix = $state('')
  let position = $state({ x: 0, y: 0 })
  let selectedIndex = $state(0)

  $effect(() => {
    const bus = editor.eventBus

    const offShow = bus.on(
      AutocompleteEvents.AUTOCOMPLETE_SHOW, (payload?: unknown) => {
        const data = payload as {
          suggestions: string[]
          prefix: string
          position: { x: number; y: number }
        }
        visible = true
        suggestions = data.suggestions
        prefix = data.prefix
        position = data.position
        selectedIndex = 0
      }
    )

    const offHide = bus.on(AutocompleteEvents.AUTOCOMPLETE_HIDE, () => {
      visible = false
      suggestions = []
      selectedIndex = 0
    })

    const offSelect = bus.on(
      AutocompleteEvents.AUTOCOMPLETE_SELECT, (payload?: unknown) => {
        if (!payload || !(payload as object).hasOwnProperty('direction')) return
        if (!visible || suggestions.length === 0) return

        const { direction } = payload as { direction: 'next' | 'previous' }
        const last = suggestions.length - 1
        selectedIndex =
          direction === 'next'
            ? (selectedIndex + 1) % suggestions.length
            : selectedIndex === 0
              ? last
              : selectedIndex - 1
      }
    )

    const offApply = bus.on(
      AutocompleteEvents.AUTOCOMPLETE_APPLY, (payload?: unknown) => {
        /* 페이로드가 있으면 이미 적용된 것이라 흘려보냅니다 */
        if (payload && (payload as object).hasOwnProperty('word')) return
        if (!visible || suggestions.length === 0) return

        bus.emit(AutocompleteEvents.AUTOCOMPLETE_APPLY, {
          word: suggestions[selectedIndex],
        })
      }
    )

    return () => {
      offShow()
      offHide()
      offSelect()
      offApply()
    }
  })

  function apply(word: string): void {
    editor.eventBus.emit(AutocompleteEvents.AUTOCOMPLETE_APPLY, { word })
  }
</script>

{#if visible && suggestions.length > 0}
  <div
    data-scope="autocomplete"
    data-part="popover"
    style="position: fixed; left: {position.x}px; top: {position.y}px; z-index: 1000"
  >
    <ul data-scope="autocomplete" data-part="list">
      {#each suggestions as word, index (word)}
        <!-- svelte-ignore a11y_click_events_have_key_events -->
        <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
        <li
          data-scope="autocomplete"
          data-part="item"
          data-selected={index === selectedIndex ? 'true' : undefined}
          onmousedown={(e) => {
            e.preventDefault()
            apply(word)
          }}
          onmouseenter={() => (selectedIndex = index)}
        >
          <span data-scope="autocomplete" data-part="prefix">{prefix}</span>
          <span data-scope="autocomplete" data-part="completion"
            >{word.slice(prefix.length)}</span
          >
        </li>
      {/each}
    </ul>
  </div>
{/if}

// packages/ui/src/components/autocomplete-popover/autocomplete-popover.tsx
import type { ComponentChildren } from 'preact'
import { useCallback, useRef, useState } from 'preact/hooks'
import { AutocompleteEvents } from 'sagak-core'
import { useEditorContext } from '../../context/editor-context'
import { useEditorEvent } from '../../hooks/use-editor-event'

interface AutocompleteState {
  visible: boolean
  suggestions: string[]
  prefix: string
  position: { x: number; y: number }
  selectedIndex: number
}

export function AutocompletePopover(): ComponentChildren {
  const context = useEditorContext()
  const [state, setState] = useState<AutocompleteState>({
    visible: false,
    suggestions: [],
    prefix: '',
    position: { x: 0, y: 0 },
    selectedIndex: 0,
  })
  const popoverRef = useRef<HTMLDivElement>(null)

  useEditorEvent(
    AutocompleteEvents.AUTOCOMPLETE_SHOW,
    'on',
    ({ suggestions, prefix, position }) => {
      setState({ visible: true, suggestions, prefix, position, selectedIndex: 0 })
    }
  )

  useEditorEvent(AutocompleteEvents.AUTOCOMPLETE_HIDE, 'on', () => {
    setState((prev) => ({
      ...prev,
      visible: false,
      suggestions: [],
      selectedIndex: 0,
    }))
  })

  useEditorEvent(AutocompleteEvents.AUTOCOMPLETE_SELECT, 'on', (payload) => {
    if (!payload || !('direction' in payload)) return
    const { direction } = payload

    setState((prev) => {
      if (!prev.visible || prev.suggestions.length === 0) return prev

      const last = prev.suggestions.length - 1
      const selectedIndex =
        direction === 'next'
          ? (prev.selectedIndex + 1) % prev.suggestions.length
          : prev.selectedIndex === 0
            ? last
            : prev.selectedIndex - 1

      return { ...prev, selectedIndex }
    })
  })

  /**
   * 페이로드가 있으면 이미 적용된 것이라 흘려보냅니다.
   * 없으면(키보드 확정) 지금 고른 단어를 실어 다시 발행합니다.
   */
  useEditorEvent(AutocompleteEvents.AUTOCOMPLETE_APPLY, 'on', (payload) => {
    if (payload && 'word' in payload) return

    setState((prev) => {
      if (!prev.visible || prev.suggestions.length === 0) return prev

      context.eventBus.emit(AutocompleteEvents.AUTOCOMPLETE_APPLY, {
        word: prev.suggestions[prev.selectedIndex],
      })

      return prev
    })
  })

  const handleItemClick = useCallback(
    (word: string) => {
      if (!context?.eventBus) return

      context.eventBus.emit(AutocompleteEvents.AUTOCOMPLETE_APPLY, { word })
    },
    [context?.eventBus]
  )

  const handleMouseEnter = useCallback((index: number) => {
    setState((prev) => ({ ...prev, selectedIndex: index }))
  }, [])

  if (!state.visible || state.suggestions.length === 0) {
    return null
  }

  return (
    <div
      ref={popoverRef}
      data-scope="autocomplete"
      data-part="popover"
      style={{
        position: 'fixed',
        left: state.position.x,
        top: state.position.y,
        zIndex: 1000,
      }}
    >
      <ul data-scope="autocomplete" data-part="list">
        {state.suggestions.map((word, index) => (
          <li
            key={word}
            data-scope="autocomplete"
            data-part="item"
            data-selected={index === state.selectedIndex ? 'true' : undefined}
            onMouseDown={(e) => {
              e.preventDefault()
              handleItemClick(word)
            }}
            onMouseEnter={() => handleMouseEnter(index)}
          >
            <span data-scope="autocomplete" data-part="prefix">
              {state.prefix}
            </span>
            <span data-scope="autocomplete" data-part="completion">
              {word.slice(state.prefix.length)}
            </span>
          </li>
        ))}
      </ul>
    </div>
  )
}
